#!/bin/bash

# Container config
VG_JUPYTER_CONTAINER_NAME="valueguard_jupyter_notebooks"
VG_JUPYTER_CONTAINER_TOKEN="iMw3pu9ERMWJEDmVOHWp9D" # CHANGE ME!
VG_JUPYTER_CONTAINER_PORT=1010

# Valueguard API config
VALUEGUARD_API_USERNAME="VALUEGUARD_API_USERNAME" # CHANGE ME!
VALUEGUARD_API_PASSWORD="VALUEGUARD_API_PASSWORD" # CHANGE ME!

docker stop $VG_JUPYTER_CONTAINER_NAME
docker rm $VG_JUPYTER_CONTAINER_NAME

docker run -d --name="$VG_JUPYTER_CONTAINER_NAME" -p$VG_JUPYTER_CONTAINER_PORT:8888 \
       -e JUPYTER_ENABLE_LAB=yes \
       -e USER=$USER \
       -e JUPYTER_TOKEN="$VG_JUPYTER_CONTAINER_TOKEN" \
       -e VALUEGUARD_API_USERNAME="$VALUEGUARD_API_USERNAME" -e VALUEGUARD_API_PASSWORD="$VALUEGUARD_API_PASSWORD" \
       -v "$PWD/notebooks":/home/jovyan/work \
       -v "$PWD/data":/home/jovyan/data \
       jupyter/datascience-notebook
